### ISSUE TITLE
SSG choice

### ISSUE THREAD

**Issue by amdomanska** [CottageLabs/website#2]
We need to choose the Static Site Generator for the website. Shortlisted options may include:

1. Hugo (adv: we have in-house experience, it is flexible, lots of documentation; dis: @richard-jones doesn't like it ;) )
2. Pelican (adv: python + jinja templates, I like the latter especially ;)  dis: we have less experience, it seems to be less popular than Hugo, therefore less support can be available)
3. Compost (adv: built by @richard-jones we can adjust it to our needs; dis: @richard-jones said it is not THAT good)

I am inclined to go with Hugo, but I'd like to hear your opinions about it.

**Comment by Steven-Eardley** [comment]
I don't have a strong opinion on these really - we use compost at the moment, which works but we should probably move off in order to have experience with what we use for production projects.

Hugo is good, pretty powerful but slightly clunky in my experience. I don't mind using it though.

I'm intrigued by Pelican - I haven't looked at it in detail but their vocabulary they talk about 'articles' - it seems setup for blogs etc, but that might suit us with our case studies etc. Minimal Python over Jinja and writing in markdown is appealing.

If it's me starting from scratch, I'd have a go with Pelican then dump it for Hugo if I don't like it. If I'm adding new pages to the existing site I'd just keep composting.

**Comment by richard-jones** [comment]
I'm happy enough with Pelican, it's nice to have stuff in a templating language we're used to.  I have never found myself that comfortable with Hugo's templating, it is bizarre.

**Comment by amdomanska** [comment]
Ok, I will have a closer look at Pelican!

**Comment by amdomanska** [comment]
After exploring both options, I have to say I'm leaning towards Hugo. It has a lot more resources, tutorials, and support available. On the other hand, I found Pelican's documentation a bit outdated and hard to navigate.

Although Hugo might not be the most straightforward initially, thanks to the resources I discovered, the learning curve seems much more manageable.

Do you mind if we go with Hugo? I think it would be a better fit for what we need. Let me know what you think!

@richard-jones @Steven-Eardley @anusharanganathan

**Comment by Steven-Eardley** [comment]
Hugo works for me, keeps things consistent with our projects.

**Comment by shshinwari** [comment]
Love

**Comment by shshinwari** [comment]
Hello I'm shshinwari
